name: CI/CD Stage

on:
  push:
    branches: [ "main", "master" ]

jobs:
  staging:
    uses: chack-check/diffaction-workflows/.github/workflows/staging.yml@main
    with:
      service-name: diffaction-organizations-service
      app-manifests: |
        kubernetes/stage/app/deployment.yml
        kubernetes/stage/app/service.yml
        kubernetes/stage/app/ingress.yml
      skiptests: true
      run-tests-command: skip
      skiplint: true
    secrets:
      KUBERNETES_SECRET: ${{ secrets.KUBERNETES_SECRET }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLIENT_SERVICE_PAT: ${{ secrets.CLIENT_SERVICE_PAT }}
